name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
    tags:
      - v*

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      FPGA_TOOLCHAIN_NIGHTLY: 20201207
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.14
      - name: Setup FPGA toolchain
        run: |
          wget -O /tmp/fpga.tar.gz https://github.com/open-tool-forge/fpga-toolchain/releases/download/nightly-$FPGA_TOOLCHAIN_NIGHTLY/fpga-toolchain-linux_x86_64-nightly-$FPGA_TOOLCHAIN_NIGHTLY.tar.gz
          tar xvf /tmp/fpga.tar.gz -C /tmp
      - name: make test
        run: env PATH=/tmp/fpga-toolchain/bin:$PATH make test
      - name: make timing
        run: env PATH=/tmp/fpga-toolchain/bin:$PATH make timing
